---
galaxy_info:
  author: emanners
  description: Install and configure an xCAT 2 management node (DHCP-less, external DDNS)
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "9"

dependencies: []