- hosts: pr2
  become: true
  roles:
    - role: mediamtx
      vars:
        mediamtx_vers: '1.19.2'
        mediamtx_arch: 'arm64'   # arm64 | armv6 | armv7
        mediamtx_url: "https://github.com/bluenviron/mediamtx/releases/download/v{{ mediamtx_vers}}/mediamtx_v{{ mediamtx_vers }}_linux_{{ mediamtx_arch }}.tar.gz"
        install_tmp_path: '/tmp'
        install_bin_path: '/usr/local/bin'
        install_cfg_path: '/usr/local/etc'
        rpiCameraHFlip: True
        rpiCameraVFlip: True
