---
# 
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
- name: 'Install the lastest Alloy Package Server'
  ansible.builtin.apt:
    deb: 'https://github.com/grafana/alloy/releases/download/v1.15.0/alloy-1.15.0-1.{{ alloy_architecture }}.deb'
    state: present
    update_cache: false

- name: 'Adding the "alloy" user to the "{{ grafana_stack_admin_group }}" group to read syslog file'
  ansible.builtin.user:
    name: 'alloy'
    groups: "{{ grafana_stack_admin_group }}"
    append: yes

- name: 'Alloy config file'
  ansible.builtin.template:
    src: 'config.alloy.j2'
    dest: '/etc/alloy/config.alloy'
    owner: 'alloy'
    group: "{{ grafana_stack_admin_group }}"

# /etc/defaults = /etc/sysconfig for debian?
- name: 'Alloy sysconfig config file'
  ansible.builtin.template:
    src: 'sysconfig_alloy.j2'
    dest: '/etc/default/alloy'
    owner: 'root'
    group: 'root'
    mode: '0640'

- name: Start service alloy, if not started
  ansible.builtin.service:
    name: alloy
    state: started
    enabled: yes
