---
# 
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
- name: 'Install the lastest Alloy Package Server'
  ansible.builtin.apt:
    #deb: https://github.com/grafana/loki/releases/download/v3.5.3/promtail_3.5.3_{{ promtail_architecture }}.deb
    deb: 'https://github.com/grafana/alloy/releases/download/v1.10.1/alloy-1.10.1-1.{{ promtail_architecture }}.deb'
    state: present
    update_cache: false

- name: 'Adding the "alloy" user to the "{{ grafana_stack_admin_group }}" group to read syslog file'
  ansible.builtin.user:
    name: 'alloy'
    groups: "{{ grafana_stack_admin_group }}"
    append: yes

- name: 'Alloy config file'
  ansible.builtin.template:
    src: 'config.alloy.j2'
    dest: '/etc/alloy/config.alloy'
    owner: 'alloy'
    group: "{{ grafana_stack_admin_group }}"

- name: Start service alloy, if not started
  ansible.builtin.service:
    name: alloy
    state: started
    enabled: yes