---
# Tasks file for alloy
# TODO: Have alloy check for promtailpromtail/

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - unbound

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
  tags:
    - unbound

# This config is based on a Docker install
#- include_tasks: docker.yml
#  when: ansible_os_family == "RedHat"
#  tags:
#    - unbound

- name: Add user emanners to the alloy group
  ansible.builtin.user:
    name: emanners
    groups: alloy
    append: yes

# TODO: Add alloy to the docker group if it exists
#- name: Add user alloy to the docker group
#  ansible.builtin.user:
#    name: allloy
#    groups: docker
#    append: yes

- name: Stop & disable the promtail service, if it exists.
  ansible.builtin.service:
    name: promtail
      state: stopped
      enabled: false
