---
# tasks file for report_alive
- name: 'Install the lastest `mailutils` package Debina'
  ansible.builtin.package:
    name: "mailutils"
    state: latest
    when: ansible_os_family == Debian

- name: 'Install the lastest `mailutils` package Redhat'
  ansible.builtin.package:
    name: "s-nail"
    state: latest
    when: ansible_os_family == Redhat

- name: "mailutils service"
  ansible.builtin.template:
    src: 'eom_report_alive.service.j2'
    dest: '/etc/systemd/system/eom_report_alive.service'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: "mailutils service file"
  ansible.builtin.template:
    src: 'eom_report_alive.sh.j2'
    dest: '/usr/local/bin/eom_report_alive.sh'
    owner: 'root'
    group: 'root'
    mode: '0755'

#- name: Change file ownership, group and permissions
#  ansible.builtin.file:
#    path: "/usr/local/bin/eom_report_alive"
#    mode: '0755'

- name: "Start service {{ package }}, if not started"
  ansible.builtin.service:
    name: eom_report_alive
    state: started
    enabled: yes
