---
# Tasks file for Influxdb 3

# Raspberry Pi 5s have a 16KB page size by default
- name: 'Add a line to the Raspberrry Pi 5 boot configuration to force 4KB page size'
  ansible.builtin.lineinfile:
    path: '/boot/firmware/config.txt'
    line: "\n# Force 4KB memory pages to fix InfluxDB 3 Core startup issue\nkernel=kernel8.img"
    create: false
    state: present

- name: 'Create Docker /opt/influxdb subdirectories for InfluxDB'
  ansible.builtin.file:
    path: /opt/influxdb
    state: directory
    mode: '0775'

- name: 'Create Docker /opt/influxdb/etc subdirectories for InfluxDB'
  ansible.builtin.file:
    path: /opt/influxdb/etc
    state: directory
    mode: '0775'

- name: 'Create Docker /opt/influxdb/data subdirectories for InfluxDB'
  ansible.builtin.file:
    path: /opt/influxdb/data
    state: directory
    mode: '0775'

- name: 'Docker create the Influxdb Container'
  community.docker.docker_container:
    name: 'influxdb'
    image: 'influxdb:3-core'
    state: started
    #restart_policy: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - /opt/influxdb/etc:/etc/influxdb
      - /opt/influxdb/data:/var/lib/influxdb
    #env:
    #  INFLUXDB_DB: "{{ influxdb_database_name }}"
    #  INFLUXDB_ADMIN_USER: "{{ influxdb_admin_user }}"
    #  INFLUXDB_ADMIN_PASSWORD: "{{ influxdb_admin_password }}"
    #  INFLUXDB_USER: "{{ influxdb_user }}"
    #  INFLUXDB_USER_PASSWORD: "{{ influxdb_user_password }}"