---
# tasks file for dhcp_server
- name: 'Install the lastest ISC DHCP Server'
  ansible.builtin.package:
    name: "{{ dhcp_package_name }}"
    state: latest

# Using user 'adm' for Debian based distros RPi and Ubuntu.
- name: 'DHCP config file'
  ansible.builtin.template:
    src: 'dhcpd.conf.j2'
    dest: "/etc/dhcp/dhcpd.conf"
    owner: 'root'
    group: "{{ dhcp_admin_group }}"
  register: dhcpd_conf

- name: 'DHCP runtime variable file'
  ansible.builtin.template:
    src: 'isc-dhcp-server.j2'
    dest: "/etc/default/isc-dhcp-server"
    owner: 'root'
    group: 'root'
  #register: dhcpd_var_conf

- name: Start service {{ dhcp_service_name }}, if not started
  ansible.builtin.service:
    name: "{{ dhcp_service_name }}"
    state: started
    enabled: yes
  when: dhcpd_conf.changed
