---
# tasks file for dhcp_server
- name: 'Install the lastest ISC DHCP Server'
  apt:
    name: "{{ service_name }}"
    state: latest

# Using user 'wheel' for RedHat based distros Rocky.
- name: 'DHCP config file'
  ansible.builtin.template:
    src: 'dhcpd.conf.j2'
    dest: "/etc/dhcp/dhcpd.conf"
    owner: 'root'
    group: "{{ admin_group }}"

- name: Start service {{ service_name }}, if not started
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: started
    enabled: yes
