- hosts: all
  become: true
  roles:
    - mediamtx
    vars:
      mtxvers: '1.11.3'
      mediamtx_url: "https://github.com/bluenviron/mediamtx/releases/download/v1.11.3/mediamtx_v1.11.3_linux_arm64v8.tar.gz"
      install_tmp_path: '/tmp'
      install_bin_path: '/usr/local/bin'
      install_cfg_path: '/usr/local/etc'
      rpiCameraHFlip: False
      rpiCameraVFlip: False
