---
# Tasks file for promtail
# https://www.osinachi.me/posts/configuring-promtail-step-by-step/

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - unbound

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
  tags:
    - unbound

# This config is based on a Docker install
#- include_tasks: docker.yml
#  when: ansible_os_family == "RedHat"
#  tags:
#    - unbound