#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/backups
#- include_tasks: firewalld.yml
- include_tasks: slurm_db.yml
  when: slurm_type == "db"

- include_tasks: slurm_compute.yml
  when: slurm_type == "compute"

- include_tasks: slurm_controller.yml
  when: slurm_type == "controller"
