#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/backups
#- include_tasks: firewalld.yml

- name: SLURM group
  ansible.builtin.group:
    name: slurm
    state: present
    gid: 1010

- name: SLURM user
  ansible.builtin.user:
    name: slurm
    comment: 'Local SLURM Service Account'
    #shell: /sbin/nologin
    groups: slurm
    uid: 1010
    state: present

- name: SLURM directories
  ansible.builtin.file:
    path: /etc/slurm
    state: directory
    owner: slurm
    group: slurm
    mode: 0775

- name: SLURM config file
  ansible.builtin.template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    owner: slurm
    group: slurm
    mode: 0664

# dd if=/dev/random of=/etc/slurm/slurm.key bs=1024 count=1
- name: 'SLURM key for auth/slurm'
  ansible.builtin.copy:
    src: slurm.key
    dest: /etc/slurm/slurm.key
    owner: slurm
    group: slurm
    mode: 0600

- name: Include SLURM database tasks if slurm_type is db
  ansible.builtin.include_tasks:
    file: 'tasks/slurm_db.yml'
  when: slurm_type == "db"

- name: Include SLURM compute tasks if slurm_type is compute
  ansible.builtin.include_tasks:
    file: 'tasks/slurm_compute.yml'
  when: slurm_type == "compute"

- name: Include SLURM controller tasks if slurm_type is controller
  ansible.builtin.include_tasks:
    file: 'tasks/slurm_controller.yml'
  when: slurm_type == "controller"
