#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/slurm
# We expect the deb_repos role to have already been run at this point
# They are configured in the meta/main.yml file for this role

- name: 'Install SLURM controller DEBs file from Katello'
  ansible.builtin.apt:
    name:
      - slurm-smd
      - slurm-smd-client
      - slurm-smd-slurmctld
    state: present
    update_cache: true

- name: 'Install SLURM controller dependencies needed for full configuration'
  ansible.builtin.apt:
    name:
      - bsd-mailx
    state: present
    update_cache: false

- name: SLURM log directories
  ansible.builtin.file:
    path: /var/log/slurm
    state: directory
    owner: slurm
    group: slurm
    mode: 0775