#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/slurm
# We expect the deb_repos role to have already been run at this point

- name: 'Install slurm compute DEBs file from Katello'
  ansible.builtin.apt:
    name:
      - slurm-smd
      - slurm-smd-client
      - slurm-smd-slurmd
    state: present
    update_cache: true
    #allow_unauthenticated: true

- name: 'SLURM compute cgroup.conf file'
  ansible.builtin.template:
    src: cgroup.conf.j2
    #dest: /etc/slurm/cgroup.conf
    dest: /usr/local/etc/cgroup.conf
    owner: slurm
    group: slurm
    mode: 0644