---
# tasks file for webhook_receiver

- name: 'Python Webhook Receiver'
  ansible.builtin.template:
    src: 'python_flask_webhook_server.py.j2'
    dest: '/usr/local/bin/webhook.py'
    mode: '0755'

- name: 'Install Pip3'
  ansible.builtin.package:
    name: 'python3-pip'
    state: latest

- name: 'Install Flask Python package'
  ansible.builtin.pip:
    name: flask

- name: 'Add SystemD service file'
  ansible.builtin.template:
    src: 'webhool_python.service.j2'
    dest: '/etc/systemd/system/webhook_python.service'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Use SystemD service for webhook'
  ansible.builtin.service:
    name: webhook_python
    state: started
    enabled: yes