---
# tasks file for r10k

# Install RPM dependencies for r10k
- name: Install the Ruby devel RPM
  ansible.builtin.dnf:
    name: ruby-devel
    state: present

- name: Install the FFI devel RPM
  ansible.builtin.dnf:
    name: libffi-devel
    state: present

- name: Install r10k gem
  community.general.gem:
    name: r10k
    install_dir: /usr/local/share/gems/gems/
    user_install: false
    version: 4.1.0
    state: present

- name: 'Create r10k config directory for r10k'
  ansible.builtin.file:
    path: /etc/puppetlabs/r10k
    state: directory
    mode: '0755'

- name: 'Create r10k config file for r10k'
  ansible.builtin.template:
    src: 'r10k.yaml.j2'
    dest: '/etc/puppetlabs/r10k/r10k.yaml'
    mode: '0755'

#- name: 'Create r10k config file for r10k'
#  ansible.builtin.template:
#    src: 'r10k.sh.j2'
#    dest: '/opt/puppetlabs/puppet/bin/r10k.sh'
#    owner: 'root'
#    group: 'root'
#    mode: '0751'