---
# Tasks file for Grafana Loki
# This config is based on a Docker install

- name: 'Create Docker /opt/loki subdirectories for Loki'
  ansible.builtin.file:
    path: /opt/loki
    state: directory
    mode: '0755'

- name: 'Create Docker /opt/loki/etc subdirectories for Loki'
  ansible.builtin.file:
    path: /opt/loki/etc
    state: directory
    mode: '0755'

- name: 'Loki config file'
  ansible.builtin.template:
    src: 'loki-config.yml.j2'
    dest: "/opt/loki/etc/loki-config.yml"
    owner: 'root'
    group: "{{ grafana_stack_admin_group }}"

- name: 'Loki Docker Compose file'
  ansible.builtin.template:
    src: 'docker-compose.yml.j2'
    dest: "/opt/loki/docker-compose.yml"
    owner: 'emanners'
    group: "{{ grafana_stack_admin_group }}"