---
# Tasks file for Grafana Loki
# This config is based on a Docker install
# https://blog.ayjc.net/posts/loki-homelab-logging/

- name: 'Create Docker /opt/loki subdirectories for Loki'
  ansible.builtin.file:
    path: /opt/loki
    state: directory
    mode: '0755'

- name: 'Create Docker /opt/loki/etc subdirectories for Loki'
  ansible.builtin.file:
    path: /opt/loki/etc
    state: directory
    mode: '0755'

- name: 'Loki config file'
  ansible.builtin.template:
    src: 'loki-config.yml.j2'
    dest: "/opt/loki/etc/loki-config.yml"
    owner: 'root'
    group: "{{ grafana_stack_admin_group }}"

- name: 'Loki Docker Compose file'
  ansible.builtin.template:
    src: 'docker-compose.yml.j2'
    dest: "/opt/loki/docker-compose.yml"
    owner: 'emanners'
    group: "{{ grafana_stack_admin_group }}"

- name: 'Docker_Create the Loki Container'
  community.docker.docker_container:
    name: 'loki'
    image: 'grafana/loki'
    state: started
    #TODO: Setup container healtcheck and switch to 'healthy'
    ports:
      - "3100:3100/tcp"
    #volumes:
    #  - '/opt/grafana/etc:/etc/grafana'
    #  - '/opt/grafana/data:/var/lib/grafana'
    user: '1001'
    restart_policy: 'unless-stopped'
    env:
      TZ: 'America/Chicago'
    platform: 'linux/arm64/v8'