---
# tasks file for eom_foreman:domain

# https://docs.ansible.com/projects/ansible/latest/collections/theforeman/foreman/domain_module.html
- name: "Create Foreman Domain"
  theforeman.foreman.domain:
    name: 'edsonmanners.com'
    description: "edsonmanners.com"
    locations:
      - "{{ location }}"
    organizations:
      - "{{ organization }}"
    state: present
    server_url: "https://{{ foreman_server }}"
    username: "ansible"
    password: "{{ ansible_user_pass }}"
    validate_certs: false