---
# tasks for managing firewalld on Foreman server
# https://docs.ansible.com/projects/ansible/latest/collections/ansible/posix/firewalld_module.html
- name: "Ensure firewalld is running and enabled"
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: "Open HTTP and HTTPS ports in firewalld"
  ansible.builtin.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  loop:
    - http
    - https