---

# https://docs.ansible.com/projects/ansible/latest/collections/theforeman/foreman/installation_medium_module.html
# Rocky Linux media entry exists out of the box in 3.19
- name: "Create Rocky Hostgroup"
  theforeman.foreman.hostgroup:
    name: "Rocky Linux"
    domain: "edsonmanners.com"
    subnet: "Houston Main Subnet"
    architecture: "x86_64"
    operatingsystem: "Rocky 9"
    medium: "Rocky Linux"
    ptable: "Kickstart default"
    state: present
    organizations:
      - "{{ organization }}"
    locations:
      - "{{ location }}"
    #
    server_url: "https://{{ foreman_server }}"
    username: "ansible"
    password: "{{ ansible_user_pass }}"
    validate_certs: false

# PiOS media needs to be added
- name: "Create PiOS Hostgroup"
  theforeman.foreman.hostgroup:
    name: "PiOS"
    domain: "edsonmanners.com"
    subnet: "Houston Main Subnet"
    architecture: "x86_64"
    operatingsystem: "Rocky 9"
    medium: "Rocky Linux"
    ptable: "Kickstart default"
    state: present
    organizations:
      - "{{ organization }}"
    locations:
      - "{{ location }}"
    #
    server_url: "https://{{ foreman_server }}"
    username: "ansible"
    password: "{{ ansible_user_pass }}"
    validate_certs: false