---
# tasks file for eom_foreman:hosts

# https://docs.ansible.com/projects/ansible/latest/collections/theforeman/foreman/host_module.html
#- name: "Create Foreman Host: {{ foreman_server }}"
#  theforeman.foreman.host:
#    name: '{{ foreman_server }}'
#    build: false
#    hostgroup: 'Rocky Linux'
#    state: present
#    location: 'Default Location'
#    organization: 'Default Organization'
#    interfaces_attributes:
#      - type: 'interface'
#        primary: true
#        #identifier: 'enp0s3'
#        mac: '08:00:27:63:85:1a'
#        subnet: 'Houston Main Subnet'
#        ip: '192.168.70.105'
#        provision: true
#    #--
#    server_url: "https://{{ foreman_server }}"
#    username: "ansible"
#    password: "{{ ansible_user_pass }}"
#    validate_certs: false

- name: "Create Infrastructure Host: infra01.edsonmanners.com"
  theforeman.foreman.host:
    name: 'infra01.edsonmanners.com'
    build: false
    hostgroup: 'Rocky Linux'
    state: present
    location: "{{ location }}"
    organization: "{{ organization }}"
    interfaces_attributes:
      - type: 'interface'
        primary: true
        #identifier: 'enp0s3'
        mac: 'a4:1f:72:93:ef:4c'
        subnet: 'Houston Main Subnet'
        ip: '192.168.68.5'
        provision: true
    #--
    server_url: "https://{{ foreman_server }}"
    username: "ansible"
    password: "{{ ansible_user_pass }}"
    validate_certs: false

- name: "Create Foreman Hosts: tp-compute-[1-4].edsonmanners.com"
  theforeman.foreman.host:
    #name: 'tp-compute-1.edsonmanners.com'
    name: "{{ item }}"
    managed: false
    hostgroup: 'Rocky Linux'
    state: present
    location: "{{ location }}"
    organization: "{{ organization }}"
    #--
    server_url: "https://{{ foreman_server }}"
    username: "ansible"
    password: "{{ ansible_user_pass }}"
    validate_certs: false
  loop:
    - tp-compute-1.edsonmanners.com
    - tp-compute-2.edsonmanners.com
    - tp-compute-3.edsonmanners.com 
    - tp-compute-4.edsonmanners.com 


