---
# tasks file for eom_foreman
- include_tasks: firewalld.yml

# https://docs.ansible.com/projects/ansible/latest/collections/theforeman/foreman/user_module.html
# Install python dependency for 'theforeman' collection
- name: "Install python3-requests on Foreman server"
  ansible.builtin.dnf:
    name: python3-requests
    state: present
- name: "Install plugins on Foreman server"
  ansible.builtin.dnf:
    name:
      - rubygem-foreman_fog_proxmox
      - rubygem-foreman_ansible
    state: present
    update_cache: yes

- include_tasks: users.yml
- include_tasks: operatingsystems.yml
- include_tasks: domains.yml
- include_tasks: subnets.yml
- include_tasks: hostgroups.yml
- include_tasks: hosts.yml
