---
# tasks file for eom_foreman
- include_tasks: firewalld.yml

# https://docs.ansible.com/projects/ansible/latest/collections/theforeman/foreman/user_module.html
# Install python dependency for 'theforeman' collection
- name: "Install python3-requests on Foreman server"
  ansible.builtin.dnf:
    name: python3-requests
    state: present
- name: "Create Ansible service account"
  theforeman.foreman.user:
    name: ansible
    firstname: Ansible
    lastname: ServiceAccount
    mail: edson.manners@gmail.com
    description: "Ansible Service Account"
    admin: false
    user_password: "{{ ansible_user_pass }}"
    auth_source: Internal
    roles:
      - 'Organization admin'
    locations:
      - "{{ location }}"
    organizations:
      - "{{ organization }}"
    server_url: "https://{{ foreman_server }}"
    username: "admin"
    password: "{{ foreman_admin_pass }}"
    state: present
    validate_certs: false

- include_tasks: operatingsystems.yml
- include_tasks: domains.yml
- include_tasks: subnets.yml
- include_tasks: hostgroups.yml
- include_tasks: hosts.yml
