---
# tasks file for eom_foreman
- include_tasks: firewalld.yml

# https://docs.ansible.com/projects/ansible/latest/collections/theforeman/foreman/user_module.html
# Install python dependency for 'theforeman' collection
- name: "Install python3-requests on Foreman server"
  ansible.builtin.dnf:
    name: python3-requests
    state: present
- name: "Create Ansible service account"
  theforeman.foreman.user:
    name: ansible
    firstname: Ansible
    lastname: ServiceAccount
    mail: edson.manners@gmail.com
    description: "TODO: Description"
    admin: false
    user_password: letmeinAS!
    auth_source: Internal
    roles:
      - 'Organization admin'
    locations:
      - "{{ location }}"
    organizations:
      - "{{ organization }}"
    server_url: "https://{{ foreman_server }}"
    username: "admin"
    password: "blewiVcxnUmeCDnPTrJo"
    state: present
    validate_certs: false

# https://docs.ansible.com/projects/ansible/latest/collections/theforeman/foreman/operatingsystem_module.html
- name: "Create an OperatingSystem"
  theforeman.foreman.operatingsystem:
    name: "Rocky_Linux"
    major: 9
    description: "Rocky 9"
    family: Redhat
    architectures:
      - "x86_64"
    ptables:
      - "Kickstart default"
    media:
      - "Rocky Linux"
    state: present
    #
    server_url: "https://{{ foreman_server }}"
    username: "ansible"
    password: "letmeinAS!"
    validate_certs: false

- include_tasks: domains.yml
- include_tasks: subnets.yml
- include_tasks: hostgroups.yml
- include_tasks: hosts.yml
