---
# Tasks file for alloy

- name: Add DEB repo file to host
  ansible.builtin.template:
    src: 'katello.list.j2'
    dest: '/etc/apt/sources.list.d/katello.list'
    owner: 'root'
    group: 'root'
    mode: '0644'

