---
# A debian/Raspberry Pi build will be a DNS Slave.
# --
- name: 'Install the lastest Bind Server'
  apt:
    name: 'bind9'
    state: 'latest'

- name: 'Bind config file'
  ansible.builtin.template:
    src: 'named.conf.options.j2'
    dest: "/etc/bind/named.conf.options"
    owner: 'root'
    group: 'bind'
    mode: '0664'

- name: 'Add sysconfig file to disable IPV6 lookups'
  ansible.builtin.template:
    src: 'default_named.j2'
    dest: '/etc/default/named'
    owner: 'root'
    group: 'bind'
    mode: '0664'

- name: 'DNS log directory'
  ansible.builtin.file:
    path: '/var/log/named'
    owner: 'root'
    group: 'named'
    mode: '0775'

- name: 'Start service named, if not started'
  ansible.builtin.service:
    name: 'named'
    state: 'started'
    enabled: 'yes'
