---
# tasks file for prometheus
- name: Create Prometheus config directory
  ansible.builtin.file:
    path: /opt/prometheus/etc
    state: directory
    owner: 'node_exporter'
    group: 'node_exporter'
    mode: 0775
    recurse: no

- name: Create Prometheus data directory
  ansible.builtin.file:
    path: /opt/prometheus/data
    state: directory
    owner: 'node_exporter'
    group: 'node_exporter'
    mode: 0775
    recurse: no

- name: Create Prometheus rules directory
  ansible.builtin.file:
    path: /opt/prometheus/data/rules
    state: directory
    owner: 'node_exporter'
    group: 'node_exporter'
    mode: 0775
    recurse: no

- name: 'Prometheus config file'
  ansible.builtin.template:
    src: 'prometheus.yml.j2'
    dest: '/opt/prometheus/etc/prometheus.yml'
    owner: 'node_exporter'
    group: 'node_exporter'
    mode: 0664

- name: 'Prometheus CPU alerts file'
  ansible.builtin.template:
    src: 'alert.cpu.yml.j2'
    dest: '/opt/prometheus/etc/alert.cpu.yml'
    owner: 'node_exporter'
    group: 'node_exporter'
    mode: 0664

- name: 'Prometheus Disk alerts file'
  ansible.builtin.template:
    src: 'alert.disk.yml.j2'
    dest: '/opt/prometheus/etc/alert.disk.yml'
    owner: 'node_exporter'
    group: 'node_exporter'
    mode: 0664


# Need a task for `docker volume create prometheus-data`
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_volume_module.html
- name: 'Docker create a volume'
  community.docker.docker_volume:
    name: prometheus-data

- name: 'Docker_Create the Prometheus Container'
  community.docker.docker_container:
    debug: yes
    #name: 'prometheus'
    name: 'prom2'
    image: 'prom/prometheus'
    state: started
      #state: healthy
    #TODO: Setup container healtcheck and switch to 'healthy'
    ports:
      - "9090:9090/tcp"
    #volumes:
    #  #- '/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    #  - '/etc/prometheus/:/opt/prometheus/etc'
    #  - 'prometheus-data:/opt/prometheus/data'
    #  #- '/opt/prometheus/data:/prometheus'
    #user: 'node_exporter'
    #user: '1001'
    #user: '296606'
    restart_policy: 'unless-stopped'
    env:
      TZ: 'America/Chicago'
    platform: 'linux/arm64'
    # The added 'v8' was causing the container to restart on Ansible run.
    # This was caught with the use of --diff on ansible run.
    #platform: 'linux/arm64/v8'
