---
# tasks file for prometheus
- name: Create Prometheus config directory
  ansible.builtin.file:
    path: /opt/prometheus/etc
    state: directory
    owner: 'nobody'
    group: 'nogroup'
    mode: 0775
    recurse: no

- name: Create Prometheus data directory
  ansible.builtin.file:
    path: /opt/prometheus/data
    state: directory
    owner: 'nobody'
    group: 'nogroup'
    mode: 0775
    recurse: no

      #- name: Create Prometheus rules directory
      #  ansible.builtin.file:
      #    path: /opt/prometheus/data/rules
      #    state: directory
      #    owner: 'nobody'
      #    group: 'nogroup'
      #    mode: 0775
      #    recurse: no\
      
- name: Create Prometheus targets directory
  ansible.builtin.file:
    path: /opt/prometheus/etc/targets
    state: directory
    owner: 'nobody'
    group: 'nogroup'
    mode: 0775
    recurse: no

- name: 'Prometheus config file'
  ansible.builtin.template:
    src: 'prometheus.yml.j2'
    dest: '/opt/prometheus/etc/prometheus.yml'
    owner: 'nobody'
    group: 'nogroup'
    mode: 0664

- name: 'Prometheus CPU alerts file'
  ansible.builtin.template:
    src: 'alert.cpu.yml.j2'
    dest: '/opt/prometheus/etc/alert.cpu.yml'
    owner: 'nobody'
    group: 'nogroup'
    mode: 0664

- name: 'Prometheus Disk alerts file'
  ansible.builtin.template:
    src: 'alert.disk.yml.j2'
    dest: '/opt/prometheus/etc/alert.disk.yml'
    owner: 'nobody'
    group: 'nogroup'
    mode: 0664

- name: 'Prometheus RAM alerts file'
  ansible.builtin.template:
    src: 'alert.ram.yml.j2'
    dest: '/opt/prometheus/etc/alert.ram.yml'
    owner: 'nobody'
    group: 'nogroup'
    mode: 0664


# Need a task for `docker volume create prometheus-data`
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_volume_module.html
- name: 'Docker create a volume'
  community.docker.docker_volume:
    name: prometheus-data

- name: 'Docker_Create the Prometheus Container'
  community.docker.docker_container:
    debug: yes
    name: 'prometheus'
    image: 'prom/prometheus'
    command: '/bin/prometheus --web.enable-remote-write-receiver'
    state: started
    ports:
      - "9090:9090/tcp"
    volumes:
      - '/opt/prometheus/etc/:/etc/prometheus/'
      #- '/opt/prometheus/etc/prometheus.yml:/etc/prometheus/prometheus.yml'
      #- '/opt/prometheus/data:/prometheus'
    #user: 'nobody'
    restart_policy: 'unless-stopped'
    env:
      TZ: 'America/Chicago'
    platform: 'linux/arm64'
    # The added 'v8' was causing the container to restart on Ansible run.
    # This was caught with the use of --diff on ansible run.
    #platform: 'linux/arm64/v8'
