---
# tasks file for prometheus
- name: Create Prometheus config directory
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    owner: emanners
    group: emanners
    mode: 0775
    recurse: no

- name: Create Prometheus data directory
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory
    owner: emanners
    group: emanners
    mode: 0775
    recurse: no

- name: 'Prometheus config file'
  ansible.builtin.template:
    src: 'prometheus.yml.j2'
    dest: '/etc/prometheus/prometheus.yml'
    owner: 'root'
    group: 'emanners'
    mode: 0664

# Need a task for `docker volume create prometheus-data`
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_volume_module.html
- name: 'Docker create a volume'
  community.docker.docker_volume:
    name: prometheus-data

- name: 'Docker_Create the Prometheus Container'
  community.docker.docker_container:
    name: 'prometheus'
    image: 'prom/prometheus'
    state: started
    #TODO: Setup container healtcheck and switch to 'healthy'
    ports:
      - "9090:9090/tcp"
    volumes:
      - '/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      #- 'prometheus-data:/prometheus'
      - '/opt/prometheus:/prometheus'
    #user: '1001'
    restart_policy: 'unless-stopped'
    env:
      TZ: 'America/Chicago'
    platform: 'linux/arm64/v8'