---
# Tasks file for telegraf

- name: 'Create Docker /opt/telegraf subdirectories for Telegraf'
  ansible.builtin.file:
    path: /opt/telegraf
    state: directory
    #owner: telegraf
    #group: telegraf
    owner: 'root'
    group: 'adm'
    mode: '0775'

- name: 'Create Docker /opt/telegraf/etc subdirectories for Telegraf'
  ansible.builtin.file:
    path: /opt/telegraf/etc
    state: directory
    owner: 'root'
    group: 'adm'
    mode: '0775'

- name: 'Telegraf config file'
  ansible.builtin.template:
    src: 'config.toml.j2'
    dest: '/opt/telegraf/etc/config.toml'
    owner: 'root'
    group: 'adm'
    mode: '0664'

- name: 'Docker create the Telegraf Container'
  community.docker.docker_container:
    name: 'telegraf'
    image: 'telegraf:latest'
    state: started
    restart_policy: unless-stopped
    volumes:
      - /opt/telegraf/etc/config.toml:/etc/telegraf/telegraf.conf:ro
    env:
      HOST_PROC: /host/proc
      HOST_SYS: /host/sys
      HOST_ETC: /host/etc
      INFLUX_TOKEN: "{{ influxdb_token }}"
      INFLUX_ORG: "{{ influxdb_organization }}"
      INFLUX_URL: "http://{{ influxdb_hostname }}:8086"
    network_mode: host
    pid_mode: host
    userns_mode: host
    capabilities:
      - SYS_PTRACE
    security_opts:
      - apparmor:unconfined